--DATEADD FUNCTION -----

SELECT 
      ORDERID ,
      ORDERDATE,
      DATEADD(YEAR,2,ORDERDATE),
      DATEADD(MONTH,3,ORDERDATE),
      DATEADD(DAY,-3,ORDERDATE) AS THREE_DAYS_EARLIER
FROM SALES.ORDERS
  

  ---DATEDIFF FUCNTION --
  -- CALCULATE THE AGE OF EMPLOYEES --

  SELECT 
        EMPLOYEEID,
        BIRTHDATE,
        DATEDIFF(YEAR,BIRTHDATE,GETDATE()) AS AGE_YEAR,
         DATEDIFF(MONTH,BIRTHDATE,GETDATE()) AS AGE_MONTHS,
          DATEDIFF(DAY,BIRTHDATE,GETDATE()) AS AGE_DAYS
        FROM SALES.Employees
       ---- FIND THE AVERAGE SHIPPIND DAYS IN A MONTH---
        SELECT
             MONTH(ORDERDATE) AS ORDERDATE,
             
            AVG(DATEDIFF(DAY,ORDERDATE,SHIPDATE)) AS AVG_DATE
       FROM SALES.ORDERS
       GROUP BY MONTH(ORDERDATE)

       ---ISSDATE FUNCTION--
          SELECT 
                ISDATE(123),
                ISDATE(2025-08-12)