--date and time function--
use salesdb
 select 
		OrderID,
		ORDERDATE,
		SHIPDATE,
		YEAR(CREATIONTIME)AS YEAR,
		MONTH(CREATIONTIME)AS MONTH,
		DAY(CREATIONTIME)AS DATE
FROM SALES.ORDERS

--- DATE PART FUNCTION--
use salesdb
 select 
		OrderID,
		ORDERDATE,
		SHIPDATE,
		YEAR(CREATIONTIME)AS YEAR,
		MONTH(CREATIONTIME)AS MONTH,
		DAY(CREATIONTIME)AS DATE,
		DATEPART(YEAR,CREATIONTIME) AS NEW_YEAR,
		DATEPART(MONTH,CREATIONTIME) AS NEW_MO,	
		DATEPART(DAY,CREATIONTIME) AS NEW_DAY,
		DATEPART(QUARTER,CREATIONTIME) AS QUAR,	
		DATEPART(WEEK,CREATIONTIME) AS WEEK_DAY
FROM SALES.ORDERS
-- DATENAME FUNCTION--
 select 
		OrderID,
		ORDERDATE,
		SHIPDATE,
		YEAR(CREATIONTIME)AS YEAR,
		MONTH(CREATIONTIME)AS MONTH,
		DAY(CREATIONTIME)AS DATE,
		DATENAME(YEAR,CREATIONTIME) AS NEW_YEAR,
		DATENAME(MONTH,CREATIONTIME) AS NEW_MO,	
		DATENAME(WEEKDAY,CREATIONTIME) AS NEW_DAY,
		DATENAME(QUARTER,CREATIONTIME) AS QUAR,	
		DATENAME(WEEK,CREATIONTIME) AS WEEK_DAY
FROM SALES.ORDERS

---DATETRUNC-----

 select 
		OrderID,
	    CREATIONTIME,
		DATETRUNC(HOUR,CREATIONTIME) AS TILL_HOUR,
		DATETRUNC(MINUTE,CREATIONTIME) AS TILL_MINUTE,
		DATETRUNC(DAY,CREATIONTIME) AS TILL_DAY,
		DATETRUNC(MONTH,CREATIONTIME) AS TILL_MONTH,
		DATETRUNC(YEAR,CREATIONTIME) AS TILL_YEAR
FROM SALES.ORDERS



---- ENDOFTHEMONTH---

 select 
		OrderID,
	    CREATIONTIME,
	    EOMONTH(CREATIONTIME) AS  MONTH, 
		DATETRUNC(MONTH,CREATIONTIME) AS STARTOFMONTH
		FROM SALES.ORDERS


		---- HOW MANY ORDERS WERE PLACED IN EACH MONTH--

				SELECT
		  DATENAME (MONTH,ORDERDATE) AS MONTHS,
			 COUNT(*) AS NOOFORDERS
			 FROM SALES.ORDERS
			 GROUP BY  DATENAME (MONTH,ORDERDATE)



			 ---FORMAT AND CASTING--

			 SELECT 
			       ORDERID,
				   creationtime as cretaion_time,
				   FORMAT( CREATIONTIME,'dd') AS DD,
				   FORMAT( CREATIONTIME,'ddd') AS dayss,
				    FORMAT( CREATIONTIME,'dddd') AS dayssd,
					FORMAT( CREATIONTIME,'MM') AS MONTHS,
						FORMAT( CREATIONTIME,'MMM') AS MONTHS,
							FORMAT( CREATIONTIME,'MMMM') AS MONTHS,
								FORMAT( CREATIONTIME,'YY') AS MONTHS
 FROM SALES.ORDERS