USE MYDATABASE
/* HVAINH CLAUSE*/
SELECT 
	COUNTRY,
	SUM(SCORE) AS TOTAL_SCORE
	FROM CUSTOMERS
	GROUP BY COUNTRY
	HAVING SUM(SCORE)>800

	/* FULL CODE TILL NOW USING ALL CLAUSES*/
	SELECT
	
			COUNTRY,
			SUM(SCORE) AS TOTAL_SCORE
   FROM customers	
		    WHERE SCORE!=0
			GROUP BY COUNTRY 
			HAVING SUM(SCORE)>700
			
			/* AVERAGE SCORE*/
			SELECT 
					COUNTRY,
					AVG(SCORE) AS TOTAL_AVERAGE
            FROM customers
			WHERE SCORE !=0
			GROUP BY country
	   
			HAVING AVG(SCORE)>430
		    ORDER BY COUNTRY DESC


			/* DUPLICATES DINTINCT FUNCTION */
			SELECT DISTINCT COUNTRY
			FROM CUSTOMERS              
			/* GROUP BY WITH DISTINCT*/
				SELECT DISTINCT COUNTRY,
				SUM(SCORE) AS TOTAL_SCORE

			FROM CUSTOMERS
			GROUP BY COUNTRY
