WITH ORDERS AS(
SELECT 1 ID , 'A' CATEGORY UNION
SELECT 2 , NULL UNION
SELECT 3 , '' UNION
SELECT 4 ' '
)
SELECT*
FROM ORDERS


;WITH ORDERS AS (
    SELECT 1 ID, 'A' CATEGORY
    UNION
    SELECT 2, NULL
    UNION
    SELECT 3, ''
    UNION
    SELECT 4,  ' '
)
SELECT *,
DATALENGTH (CATEGORY) CATEGORYLEN
FROM ORDERS;