--FIND AVERAGE SCORE ODF THE CUSTOMERS --
SELECT 
      ID,
      FIRST_NAME,
      SCORE,
AVG(SCORE) OVER() AVGSCORES
FROM CUSTOMERS

/*DISPLAY FULL NAME OF CUSTOMERS IN A SINGLE FILLED BY JOINING FIRST NAME AND THE LAST NAME 
AND  ADD 10 BONUS POINTS FOR EACH CUSTOMER SCORE */
   SELECT 
         CUSTOMERID ,
         FIRSTNAME,
         LASTNAME,
         FIRSTNAME + '' + COALESCE(LASTNAME,'') AS FULLNAME,
         SCORE,
         COALESCE (SCORE,0)+10AS NEW_SCORE
FROM SALES.CUSTOMERS


---- SORT THE SCORETHE LOWEST OT THE HIGHEST  WITH NULLS APPEARING AT LAST --
SELECT 
      CUSTOMERID,
      FIRSTNAME,
      SCORE
FROM SALES.CUSTOMERS
ORDER BY SCORE DESC