---RETRIEVE ALL CUSTOMERS WHOSE COUNTRY IS USA*--   COMPARISON OPERATOR


SELECT*
 FROM CUSTOMERS 
 WHERE COUNTRY='USA'

 --RETREIVE ALL CUSTOMERS WHOLE SCORE IS =500--
 SELECT*
 FROM CUSTOMERS 
 WHERE  SCORE=500
 
 --RETREIVE ALL CUSTOMERS WHOLE SCORE IS >500--
  SELECT*
 FROM CUSTOMERS 
 WHERE  SCORE>500
  --RETREIVE ALL CUSTOMERS WHOLE SCORE IS <500--
  SELECT*
 FROM CUSTOMERS 
 WHERE  SCORE<500
  --RETREIVE ALL CUSTOMERS WHOLE SCORE IS >=500--
  SELECT*
 FROM CUSTOMERS 
 WHERE  SCORE>=500
  --RETREIVE ALL CUSTOMERS WHOLE SCORE IS <=500--
  SELECT*
 FROM CUSTOMERS 
 WHERE  SCORE<=500
  --RETREIVE ALL CUSTOMERS WHOLE SCORE IS NOT EQUAL500--
  SELECT*
 FROM CUSTOMERS 
 WHERE  SCORE!=500



 --- LOGICAL OPERATOR--
 --RETREIVE ALL CUSTOMERS WHOSE COUNTRY IS USA AND SCORE IS GREATOR THEN 500
 SELECT *
 FROM CUSTOMERS 
 WHERE COUNTRY='USA' AND SCORE >500
  --RETREIVE ALL CUSTOMERS WHOSE COUNTRY IS USA AND SCORE IS SMALLER THEN 500
 SELECT *
 FROM CUSTOMERS 
 WHERE COUNTRY='USA' AND SCORE <500

  --RETREIVE ALL CUSTOMERS WHOSE COUNTRY IS USA OR SCORE IS GREATOR THEN 500
 SELECT *
 FROM CUSTOMERS 
 WHERE COUNTRY='USA' OR SCORE >500


  --RETREIVE ALL CUSTOMERS WHOSE COUNTRY IS NOT  USA  SCORE IS GREATOR THEN 500
 SELECT *
 FROM CUSTOMERS 
 WHERE NOT COUNTRY='USA' AND SCORE >500

 --- MEMBERSHIP OPERATOR --
 -- USED TO FIND VALUES IN A LIST IN AND NOT IN---

  SELECT *
   FROM CUSTOMERS 
   WHERE COUNTRY IN ('USA','GERMANY')

   -- MULTIPLE VALUES
    --RETREIVE ALL CUSTOMERS WHOSE COUNTRY IS USA AND SCORE IS GREATOR THEN 500
 SELECT *
 FROM CUSTOMERS 
 WHERE COUNTRY IN ('USA', 'GERMANY','UK')
 -- NOT IN
 SELECT *
 FROM CUSTOMERS 
 WHERE COUNTRY NOT IN ('USA', 'GERMANY','UK')
 --- SEARCH OPERATOR --
 SELECT *
 FROM CUSTOMERS 
 WHERE first_name like 'M%'
